### ISSUE TITLE
Can't install or use it

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [arigit/lastwake.py#13]
On Ubuntu ~20.04~ 18.04, I did:

    git clone https://github.com/arigit/lastwake.py.git
    cd lastwake.py
    
then:

    $ pip3 install -r requirements.txt 
    Collecting systemd-python (from -r requirements.txt (line 1))
      Downloading https://files.pythonhosted.org/packages/e8/a8/00ba0f605837a8f69523e6c3a4fb14675a6430c163f836540129c50b3aef/systemd-python-234.tar.gz (53kB)
        100% |████████████████████████████████| 61kB 458kB/s 
        Complete output from command python setup.py egg_info:
        Cannot find libsystemd or libsystemd-journal:
        
        Package libsystemd was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libsystemd.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libsystemd' found
        
        Package libsystemd-journal was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libsystemd-journal.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libsystemd-journal' found
        
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uktheja8/systemd-python/

And trying to use it:

    $ ./lastwake.py 

    Wake/Sleep Time SystemD Journal Analyzer

     Boot under analysis: current boot
    Traceback (most recent call last):
      File "./lastwake.py", line 92, in <module>
        bootTime = j.get_next()['__REALTIME_TIMESTAMP']
    KeyError: '__REALTIME_TIMESTAMP'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "./lastwake.py", line 94, in <module>
        print("\n Warning: no entries in the Journal found for boot: " + bootId + " (script terminated)\n")
    TypeError: must be str, not NoneType

**Comment by arigit** [comment]
I have this working on ubuntu 20.04 with no issues.
I believe you may be missing a library dependency, please try:

`sudo apt install  libsystemd-dev`

And then reattempt to install the python requirements.
If this works I will add this as the first installation step

**Comment by ElectricRCAircraftGuy** [comment]
Correction: I was on Ubuntu 18.04, not 20.04. Installing that dependency before calling the `pip3 install -r requirements.txt` command does indeed make the requirements install work now! (so I *do* recommend you add that as a first step for installation). But, I still can't run the program:

```
$ ./lastwake.py 

Wake/Sleep Time SystemD Journal Analyzer

 Boot under analysis: current boot
Traceback (most recent call last):
  File "./lastwake.py", line 92, in <module>
    bootTime = j.get_next()['__REALTIME_TIMESTAMP']
KeyError: '__REALTIME_TIMESTAMP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lastwake.py", line 94, in <module>
    print("\n Warning: no entries in the Journal found for boot: " + bootId + " (script terminated)\n")
TypeError: must be str, not NoneType

```

**Comment by arigit** [comment]
I committed a small change that will prevent the error, and also improved the installation instructions.

However, note that your scenario only happens when the journal has zero entries for the bootID under analysis, which is the current boot assuming you have not invoked any command line option.

You can inspect your journal entries by trying,

```
journalctl -b
```

If the output you get is "no-entries" then that will confirm your journal is empty. In that case you will need to troubleshoot your system's journal that may have been corrupted for some reason. Once that is fixed this script will work.

If you find that your journal has entries and this script shows "no entries in Journal found" then please reopen this

**Comment by ElectricRCAircraftGuy** [comment]
Reopening. Note that I've created this PR to improve your README: https://github.com/arigit/lastwake.py/pull/14. 

Also, `lastwake` now shows the following, with your latest change:

```
$ lastwake 

Wake/Sleep Time SystemD Journal Analyzer

 Boot under analysis: current boot

 Warning: no entries in the Journal found for current boot (script terminated)
```

Yet, my `journalctl -b` output shows 16000 lines (I did `journalctl -b > journal.txt` and viewed it in a text editor). It's definitely not empty.

**Comment by ElectricRCAircraftGuy** [comment]
If this helps, here's what I manually get in my `out` variable:
```python
$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from systemd import journal
>>> j = journal.Reader(journal.SYSTEM)
>>> j
<systemd.journal.Reader object at 0x7f51d9946088>
>>> print(j)
<systemd.journal.Reader object at 0x7f51d9946088>
>>> j.this_boot(bootId)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bootId' is not defined
>>> j.get_next()
{}
>>> import subprocess
>>> out = subprocess.check_output(["journalctl",
...                                        "--list-boots"]).decode('utf-8')
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
>>> out
'-36 d4cee7c19d09405ca78afcc23b2aafe9 Thu 2020-03-26 17:45:44 PDT—Mon 2020-03-30 15:22:59 PDT\n-35 4a15a850ab014a3c824aab2e7c9ac02e Mon 2020-03-30 15:25:25 PDT—Thu 2020-04-09 10:04:18 PDT\n-34 7e683b8571c4450b9e1a1859bc1281e6 Thu 2020-04-09 10:06:41 PDT—Thu 2020-04-09 15:38:28 PDT\n-33 dfb35c6f191547a38b8530af997fbb12 Thu 2020-04-09 15:40:09 PDT—Fri 2020-04-10 11:28:55 PDT\n-32 98b6a65485d44cf7be0e7f7098f6266e Fri 2020-04-10 11:29:42 PDT—Tue 2020-04-14 10:31:35 PDT\n-31 453c3096c774455682a0a875a5d0e7e8 Tue 2020-04-14 10:35:36 PDT—Fri 2020-04-17 12:20:32 PDT\n-30 a758983b3cc1458b8da1b90b067b72df Fri 2020-04-17 12:56:38 PDT—Tue 2020-04-28 10:37:50 PDT\n-29 8127593a8b3e4c0cacdfdbb92a9770da Tue 2020-04-28 10:40:58 PDT—Tue 2020-05-05 10:03:17 PDT\n-28 b077f3628d0a48a685c0fb2bb5ee3cc0 Tue 2020-05-05 10:05:48 PDT—Wed 2020-05-20 13:59:52 PDT\n-27 bd34eee98a3a4c37b7367723e1023633 Wed 2020-05-20 14:02:01 PDT—Fri 2020-05-29 15:14:14 PDT\n-26 359d0cf473284dfe870abd53f3200774 Fri 2020-05-29 15:18:39 PDT—Fri 2020-06-12 15:44:25 PDT\n-25 068b8136874649d88715c56d147e3802 Fri 2020-06-12 15:47:59 PDT—Sat 2020-06-27 16:49:45 PDT\n-24 4b345d8cab294afd9eb1e2842bbe9ca2 Sat 2020-06-27 16:51:56 PDT—Sat 2020-06-27 17:11:18 PDT\n-23 bcc93910242f4956a16b74fdff0e5be5 Sat 2020-06-27 17:13:46 PDT—Sun 2020-06-28 17:15:10 PDT\n-22 992fb31c63154e00855bf876a0a8d59f Sun 2020-06-28 17:18:16 PDT—Sun 2020-06-28 17:19:57 PDT\n-21 f0f7c5b84b22497d9e8368e08d6b4ccc Sun 2020-06-28 17:21:17 PDT—Sun 2020-06-28 17:29:38 PDT\n-20 37707828985e4f38ae1463a5505549ba Sun 2020-06-28 17:30:58 PDT—Tue 2020-06-30 10:05:01 PDT\n-19 d8ae920f88fb4decae2db6bda7880be5 Tue 2020-06-30 10:07:21 PDT—Thu 2020-07-16 09:59:17 PDT\n-18 3eb4d054dcae4545bd4a7a706aec712b Thu 2020-07-16 10:00:38 PDT—Mon 2020-08-10 10:05:56 PDT\n-17 2269657f9f8641dbaa33e4ffb7857051 Mon 2020-08-10 10:07:51 PDT—Wed 2020-08-19 12:18:44 PDT\n-16 4a0faccb737b47b4a0a0ea41ec7c33cf Wed 2020-08-19 12:21:19 PDT—Tue 2020-09-01 15:42:29 PDT\n-15 5368d0966ad14b83bd72b18c8beee273 Tue 2020-09-01 15:44:49 PDT—Wed 2020-09-02 21:55:03 PDT\n-14 4d689659f3534c5bb20359348c5afc29 Wed 2020-09-02 21:57:46 PDT—Sat 2020-09-05 14:44:50 PDT\n-13 a37cb0c7de944c44a3333d6c9cd698f4 Tue 2020-09-08 08:37:40 PDT—Sat 2020-09-12 22:52:36 PDT\n-12 7dc8d5fc4ccf416c84861e681d1bb083 Sat 2020-09-12 22:56:26 PDT—Tue 2020-09-15 13:29:50 PDT\n-11 01e2fc94e885496e8262f41aa6828c60 Tue 2020-09-15 13:31:46 PDT—Thu 2020-09-17 11:37:11 PDT\n-10 e2f5ce2b7bca480889d9b93de0ddbac3 Thu 2020-09-17 11:38:41 PDT—Sun 2020-09-20 17:55:25 PDT\n -9 8181f39f13354a048c5adaeea95ee643 Sun 2020-09-20 18:22:50 PDT—Mon 2020-09-21 21:53:37 PDT\n -8 1e116e450e8f4e3390e02680d5da8183 Tue 2020-09-22 08:57:19 PDT—Wed 2020-09-23 10:53:19 PDT\n -7 ec70d3fb00c449a4abc32db75c464957 Wed 2020-09-23 10:54:40 PDT—Fri 2020-09-25 15:29:05 PDT\n -6 c862dcf18b7142e488169ecf55b84102 Fri 2020-09-25 15:31:26 PDT—Sun 2020-10-04 11:38:23 PDT\n -5 ea5c3036a6144434943139535139c875 Mon 2020-10-05 10:56:18 PDT—Mon 2020-10-05 22:15:00 PDT\n -4 68b3a735ab5e43dbac3a607c25b891f3 Tue 2020-10-06 12:57:14 PDT—Tue 2020-10-06 18:13:10 PDT\n -3 6def208328a84221b6029bb721d6645e Tue 2020-10-06 18:31:00 PDT—Tue 2020-10-06 21:31:26 PDT\n -2 a2364ecd81cc45e08e7f55561b0843f0 Wed 2020-10-07 11:09:01 PDT—Thu 2020-10-08 11:21:26 PDT\n -1 06c6734e49e743d2ad6eb1b58bc9dec9 Thu 2020-10-08 11:26:32 PDT—Thu 2020-10-15 13:04:15 PDT\n  0 7f5b3278f62749179636b79b96af611e Thu 2020-10-15 13:06:51 PDT—Sun 2020-10-18 12:21:08 PDT\n'
```

Here's just those last 2 lines, with line wrapping:

>>> out
'-36 d4cee7c19d09405ca78afcc23b2aafe9 Thu 2020-03-26 17:45:44 PDT—Mon 2020-03-30 15:22:59 PDT\n-35 4a15a850ab014a3c824aab2e7c9ac02e Mon 2020-03-30 15:25:25 PDT—Thu 2020-04-09 10:04:18 PDT\n-34 7e683b8571c4450b9e1a1859bc1281e6 Thu 2020-04-09 10:06:41 PDT—Thu 2020-04-09 15:38:28 PDT\n-33 dfb35c6f191547a38b8530af997fbb12 Thu 2020-04-09 15:40:09 PDT—Fri 2020-04-10 11:28:55 PDT\n-32 98b6a65485d44cf7be0e7f7098f6266e Fri 2020-04-10 11:29:42 PDT—Tue 2020-04-14 10:31:35 PDT\n-31 453c3096c774455682a0a875a5d0e7e8 Tue 2020-04-14 10:35:36 PDT—Fri 2020-04-17 12:20:32 PDT\n-30 a758983b3cc1458b8da1b90b067b72df Fri 2020-04-17 12:56:38 PDT—Tue 2020-04-28 10:37:50 PDT\n-29 8127593a8b3e4c0cacdfdbb92a9770da Tue 2020-04-28 10:40:58 PDT—Tue 2020-05-05 10:03:17 PDT\n-28 b077f3628d0a48a685c0fb2bb5ee3cc0 Tue 2020-05-05 10:05:48 PDT—Wed 2020-05-20 13:59:52 PDT\n-27 bd34eee98a3a4c37b7367723e1023633 Wed 2020-05-20 14:02:01 PDT—Fri 2020-05-29 15:14:14 PDT\n-26 359d0cf473284dfe870abd53f3200774 Fri 2020-05-29 15:18:39 PDT—Fri 2020-06-12 15:44:25 PDT\n-25 068b8136874649d88715c56d147e3802 Fri 2020-06-12 15:47:59 PDT—Sat 2020-06-27 16:49:45 PDT\n-24 4b345d8cab294afd9eb1e2842bbe9ca2 Sat 2020-06-27 16:51:56 PDT—Sat 2020-06-27 17:11:18 PDT\n-23 bcc93910242f4956a16b74fdff0e5be5 Sat 2020-06-27 17:13:46 PDT—Sun 2020-06-28 17:15:10 PDT\n-22 992fb31c63154e00855bf876a0a8d59f Sun 2020-06-28 17:18:16 PDT—Sun 2020-06-28 17:19:57 PDT\n-21 f0f7c5b84b22497d9e8368e08d6b4ccc Sun 2020-06-28 17:21:17 PDT—Sun 2020-06-28 17:29:38 PDT\n-20 37707828985e4f38ae1463a5505549ba Sun 2020-06-28 17:30:58 PDT—Tue 2020-06-30 10:05:01 PDT\n-19 d8ae920f88fb4decae2db6bda7880be5 Tue 2020-06-30 10:07:21 PDT—Thu 2020-07-16 09:59:17 PDT\n-18 3eb4d054dcae4545bd4a7a706aec712b Thu 2020-07-16 10:00:38 PDT—Mon 2020-08-10 10:05:56 PDT\n-17 2269657f9f8641dbaa33e4ffb7857051 Mon 2020-08-10 10:07:51 PDT—Wed 2020-08-19 12:18:44 PDT\n-16 4a0faccb737b47b4a0a0ea41ec7c33cf Wed 2020-08-19 12:21:19 PDT—Tue 2020-09-01 15:42:29 PDT\n-15 5368d0966ad14b83bd72b18c8beee273 Tue 2020-09-01 15:44:49 PDT—Wed 2020-09-02 21:55:03 PDT\n-14 4d689659f3534c5bb20359348c5afc29 Wed 2020-09-02 21:57:46 PDT—Sat 2020-09-05 14:44:50 PDT\n-13 a37cb0c7de944c44a3333d6c9cd698f4 Tue 2020-09-08 08:37:40 PDT—Sat 2020-09-12 22:52:36 PDT\n-12 7dc8d5fc4ccf416c84861e681d1bb083 Sat 2020-09-12 22:56:26 PDT—Tue 2020-09-15 13:29:50 PDT\n-11 01e2fc94e885496e8262f41aa6828c60 Tue 2020-09-15 13:31:46 PDT—Thu 2020-09-17 11:37:11 PDT\n-10 e2f5ce2b7bca480889d9b93de0ddbac3 Thu 2020-09-17 11:38:41 PDT—Sun 2020-09-20 17:55:25 PDT\n -9 8181f39f13354a048c5adaeea95ee643 Sun 2020-09-20 18:22:50 PDT—Mon 2020-09-21 21:53:37 PDT\n -8 1e116e450e8f4e3390e02680d5da8183 Tue 2020-09-22 08:57:19 PDT—Wed 2020-09-23 10:53:19 PDT\n -7 ec70d3fb00c449a4abc32db75c464957 Wed 2020-09-23 10:54:40 PDT—Fri 2020-09-25 15:29:05 PDT\n -6 c862dcf18b7142e488169ecf55b84102 Fri 2020-09-25 15:31:26 PDT—Sun 2020-10-04 11:38:23 PDT\n -5 ea5c3036a6144434943139535139c875 Mon 2020-10-05 10:56:18 PDT—Mon 2020-10-05 22:15:00 PDT\n -4 68b3a735ab5e43dbac3a607c25b891f3 Tue 2020-10-06 12:57:14 PDT—Tue 2020-10-06 18:13:10 PDT\n -3 6def208328a84221b6029bb721d6645e Tue 2020-10-06 18:31:00 PDT—Tue 2020-10-06 21:31:26 PDT\n -2 a2364ecd81cc45e08e7f55561b0843f0 Wed 2020-10-07 11:09:01 PDT—Thu 2020-10-08 11:21:26 PDT\n -1 06c6734e49e743d2ad6eb1b58bc9dec9 Thu 2020-10-08 11:26:32 PDT—Thu 2020-10-15 13:04:15 PDT\n  0 7f5b3278f62749179636b79b96af611e Thu 2020-10-15 13:06:51 PDT—Sun 2020-10-18 12:21:08 PDT\n'

**Comment by ElectricRCAircraftGuy** [comment]
And here's the output from `journalctl --list-boots`:

```
$ journalctl --list-boots 
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-36 d4cee7c19d09405ca78afcc23b2aafe9 Thu 2020-03-26 17:45:44 PDT—Mon 2020-03-30 15:22:59 PDT
-35 4a15a850ab014a3c824aab2e7c9ac02e Mon 2020-03-30 15:25:25 PDT—Thu 2020-04-09 10:04:18 PDT
-34 7e683b8571c4450b9e1a1859bc1281e6 Thu 2020-04-09 10:06:41 PDT—Thu 2020-04-09 15:38:28 PDT
-33 dfb35c6f191547a38b8530af997fbb12 Thu 2020-04-09 15:40:09 PDT—Fri 2020-04-10 11:28:55 PDT
-32 98b6a65485d44cf7be0e7f7098f6266e Fri 2020-04-10 11:29:42 PDT—Tue 2020-04-14 10:31:35 PDT
-31 453c3096c774455682a0a875a5d0e7e8 Tue 2020-04-14 10:35:36 PDT—Fri 2020-04-17 12:20:32 PDT
-30 a758983b3cc1458b8da1b90b067b72df Fri 2020-04-17 12:56:38 PDT—Tue 2020-04-28 10:37:50 PDT
-29 8127593a8b3e4c0cacdfdbb92a9770da Tue 2020-04-28 10:40:58 PDT—Tue 2020-05-05 10:03:17 PDT
-28 b077f3628d0a48a685c0fb2bb5ee3cc0 Tue 2020-05-05 10:05:48 PDT—Wed 2020-05-20 13:59:52 PDT
-27 bd34eee98a3a4c37b7367723e1023633 Wed 2020-05-20 14:02:01 PDT—Fri 2020-05-29 15:14:14 PDT
-26 359d0cf473284dfe870abd53f3200774 Fri 2020-05-29 15:18:39 PDT—Fri 2020-06-12 15:44:25 PDT
-25 068b8136874649d88715c56d147e3802 Fri 2020-06-12 15:47:59 PDT—Sat 2020-06-27 16:49:45 PDT
-24 4b345d8cab294afd9eb1e2842bbe9ca2 Sat 2020-06-27 16:51:56 PDT—Sat 2020-06-27 17:11:18 PDT
-23 bcc93910242f4956a16b74fdff0e5be5 Sat 2020-06-27 17:13:46 PDT—Sun 2020-06-28 17:15:10 PDT
-22 992fb31c63154e00855bf876a0a8d59f Sun 2020-06-28 17:18:16 PDT—Sun 2020-06-28 17:19:57 PDT
-21 f0f7c5b84b22497d9e8368e08d6b4ccc Sun 2020-06-28 17:21:17 PDT—Sun 2020-06-28 17:29:38 PDT
-20 37707828985e4f38ae1463a5505549ba Sun 2020-06-28 17:30:58 PDT—Tue 2020-06-30 10:05:01 PDT
-19 d8ae920f88fb4decae2db6bda7880be5 Tue 2020-06-30 10:07:21 PDT—Thu 2020-07-16 09:59:17 PDT
-18 3eb4d054dcae4545bd4a7a706aec712b Thu 2020-07-16 10:00:38 PDT—Mon 2020-08-10 10:05:56 PDT
-17 2269657f9f8641dbaa33e4ffb7857051 Mon 2020-08-10 10:07:51 PDT—Wed 2020-08-19 12:18:44 PDT
-16 4a0faccb737b47b4a0a0ea41ec7c33cf Wed 2020-08-19 12:21:19 PDT—Tue 2020-09-01 15:42:29 PDT
-15 5368d0966ad14b83bd72b18c8beee273 Tue 2020-09-01 15:44:49 PDT—Wed 2020-09-02 21:55:03 PDT
-14 4d689659f3534c5bb20359348c5afc29 Wed 2020-09-02 21:57:46 PDT—Sat 2020-09-05 14:44:50 PDT
-13 a37cb0c7de944c44a3333d6c9cd698f4 Tue 2020-09-08 08:37:40 PDT—Sat 2020-09-12 22:52:36 PDT
-12 7dc8d5fc4ccf416c84861e681d1bb083 Sat 2020-09-12 22:56:26 PDT—Tue 2020-09-15 13:29:50 PDT
-11 01e2fc94e885496e8262f41aa6828c60 Tue 2020-09-15 13:31:46 PDT—Thu 2020-09-17 11:37:11 PDT
-10 e2f5ce2b7bca480889d9b93de0ddbac3 Thu 2020-09-17 11:38:41 PDT—Sun 2020-09-20 17:55:25 PDT
 -9 8181f39f13354a048c5adaeea95ee643 Sun 2020-09-20 18:22:50 PDT—Mon 2020-09-21 21:53:37 PDT
 -8 1e116e450e8f4e3390e02680d5da8183 Tue 2020-09-22 08:57:19 PDT—Wed 2020-09-23 10:53:19 PDT
 -7 ec70d3fb00c449a4abc32db75c464957 Wed 2020-09-23 10:54:40 PDT—Fri 2020-09-25 15:29:05 PDT
 -6 c862dcf18b7142e488169ecf55b84102 Fri 2020-09-25 15:31:26 PDT—Sun 2020-10-04 11:38:23 PDT
 -5 ea5c3036a6144434943139535139c875 Mon 2020-10-05 10:56:18 PDT—Mon 2020-10-05 22:15:00 PDT
 -4 68b3a735ab5e43dbac3a607c25b891f3 Tue 2020-10-06 12:57:14 PDT—Tue 2020-10-06 18:13:10 PDT
 -3 6def208328a84221b6029bb721d6645e Tue 2020-10-06 18:31:00 PDT—Tue 2020-10-06 21:31:26 PDT
 -2 a2364ecd81cc45e08e7f55561b0843f0 Wed 2020-10-07 11:09:01 PDT—Thu 2020-10-08 11:21:26 PDT
 -1 06c6734e49e743d2ad6eb1b58bc9dec9 Thu 2020-10-08 11:26:32 PDT—Thu 2020-10-15 13:04:15 PDT
  0 7f5b3278f62749179636b79b96af611e Thu 2020-10-15 13:06:51 PDT—Sun 2020-10-18 12:16:08 PDT
```

**Note: it looks like I don't have permissions to re-open this issue.**

**Comment by arigit** [comment]
Reopened

Try this please

```
lastwake -b 06c6734e49e743d2ad6eb1b58bc9dec9
```

let's see if it finds timestamps, this is your prior-to-current boot. 
BTW I am using both 18.04 an 20.04 myself with no issues.

If the above works, then there is a problem with systemd journal timestamp logging in your current boot

To debug further, for the interpreter test, try this,

```
>>> from systemd import journal
>>> j = journal.Reader(journal.SYSTEM)
>>> j.this_boot(None)
>>> j.add_conjunction()
>>> j.log_level(journal.LOG_DEBUG)
>>> j.get_next()['__REALTIME_TIMESTAMP']
datetime.datetime(2020, 9, 30, 18, 53, 36, 507786)
```

this should print the date of the first event of the current boot. If you get an error, try changing the boot id, for example try
>>> j.this_boot(06c6734e49e743d2ad6eb1b58bc9dec9)

If changing the bootID works but using 'None' (current boot) doesn't then again this points to something strange going on with the journal in your system. Let's see what you find

**Comment by arigit** [comment]
closing due to no activity
